// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApiForm: typeof import('./components/form/ApiForm.vue')['default']
    AppBreadcrumb: typeof import('./components/AppBreadcrumb.vue')['default']
    AppPage: typeof import('./components/AppPage.vue')['default']
    AuthMetaInfoSection: typeof import('./components/AuthMetaInfoSection.vue')['default']
    BaseBackground: typeof import('./components/BaseBackground.vue')['default']
    BaseBlock: typeof import('./components/BaseBlock.vue')['default']
    BaseNavigation: typeof import('./components/BaseNavigation.vue')['default']
    BasePageHeading: typeof import('./components/BasePageHeading.vue')['default']
    Checkbox: typeof import('./components/form/Checkbox.vue')['default']
    CloseButton: typeof import('./components/form/CloseButton.vue')['default']
    CommandCell: typeof import('./layouts/partials/CommandCell.vue')['default']
    ConfirmDelete: typeof import('./components/form/ConfirmDelete.vue')['default']
    DropDownCell: typeof import('./components/grids/DropDownCell.vue')['default']
    ErrorSummary: typeof import('./components/form/ErrorSummary.vue')['default']
    FluentAddCircle24Regular: typeof import('~icons/fluent/add-circle24-regular')['default']
    FormLoading: typeof import('./components/form/FormLoading.vue')['default']
    GettingStarted: typeof import('./components/GettingStarted.vue')['default']
    HelloApi: typeof import('./components/HelloApi.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputDescription: typeof import('./components/form/InputDescription.vue')['default']
    LogosVue: typeof import('~icons/logos/vue')['default']
    MarkdownPage: typeof import('./components/MarkdownPage.vue')['default']
    MdiCloseCircle: typeof import('~icons/mdi/close-circle')['default']
    MdiSquareEditOutline: typeof import('~icons/mdi/square-edit-outline')['default']
    NavFooter: typeof import('./components/NavFooter.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    OutlineButton: typeof import('./components/form/OutlineButton.vue')['default']
    PrimaryButton: typeof import('./components/form/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./components/form/SecondaryButton.vue')['default']
    SelectInput: typeof import('./components/form/SelectInput.vue')['default']
    ShellCommand: typeof import('./components/ShellCommand.vue')['default']
    SrcLink: typeof import('./components/SrcLink.vue')['default']
    TextAreaInput: typeof import('./components/form/TextAreaInput.vue')['default']
    TextInput: typeof import('./components/form/TextInput.vue')['default']
  }
}
