version: "3.9"
services:
  ${APP_NAME}:
    image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
    restart: always
    # expose:
    #  - 3000
    # networks:
    #   service_network:
    network_mode: bridge
    ports:
      - "80"
    # networks:
    #   - proxy
    # ports:
    #   - mode: ingress
    #     target: 80
    #     published: 80
    #     protocol: tcp
    #   - mode: ingress
    #     target: 443
    #     published: 443
    #     protocol: tcp
    environment:
      # HTTP_PORT: 8000
      DEFAULT_HOST: apps.ptgdi.com
      VIRTUAL_HOST: localhost, apps.ptgdi.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: localhost, apps.ptgdi.com
      LETSENCRYPT_EMAIL: rialdi@ptgdi.com
      DEPLOY_API: ${DEPLOY_API}
      DEPLOY_CDN: ${DEPLOY_CDN}
    volumes:
      - ${APP_NAME}-mydb:/app/App_Data

  ${APP_NAME}-migration:
    image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
    restart: "no"
    profiles:
      - migration
    command: --AppTasks=migrate
    volumes:
      - ${APP_NAME}-mydb:/app/App_Data

volumes:
  ${APP_NAME}-mydb:

# networks:
#   service_network:
