name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install and build npm
      run: |
        npm install
        npm run build
      working-directory: ./ui
    
    - name: Activate Kendo UI License
      run: npx kendo-ui-license activate
      # Set working directory if the application is not in the repository root folder:
      # working-directory: 'ClientApp'
      working-directory: ./ui
      env:
        KENDO_UI_LICENSE: ${{ secrets.KENDO_UI_LICENSE }}
      

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: true
    - name: Build
      run: dotnet build ./api
    - name: Test
      run: dotnet test ./api/GDIApps.Tests
