// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowProjectGDIApps.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SimpleOvertime")]
    public partial class SimpleOvertimeFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "SimpleOvertime.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "SimpleOvertime", "A short summary of the feature\r\n***Mockup:***\r\n![Create Claim Mockup](./Mockups/C" +
                    "reateClaim.png)", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "EMPLOYEE_ID",
                        "NAME",
                        "POSITION_ID",
                        "POS_DEPT",
                        "SUPERIOR_NAME",
                        "SUPERIOR_POS",
                        "MOR_NAME",
                        "MOR_POS"});
            table12.AddRow(new string[] {
                        "0000007142",
                        "NASARUDDIN",
                        "FPOCR4",
                        "SMELTER FURNACE",
                        "0000005664 - MUJAHID LAOLA",
                        "E00124 - SUPV, FURNACE SHIFT D",
                        "0000008989 - REZA PRIBADI UMBARA",
                        "DPPGM5 - MGR, SMELTER FURNAC"});
#line 7
testRunner.Given("Exist Following Employees Data From Common Service", ((string)(null)), table12, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "EMPLOYEE_ID",
                        "FULL_NAME",
                        "USERNAME",
                        "EMAIL"});
            table13.AddRow(new string[] {
                        "0000007142",
                        "NASARUDIN",
                        "nzr150",
                        "nasarudin@vale.com"});
            table13.AddRow(new string[] {
                        "0000005664",
                        "MUJAHID LAOLA",
                        "mu3210",
                        "mujahid.laola@vale.com"});
            table13.AddRow(new string[] {
                        "0000008989",
                        "REZA PRIBADI UMBARA",
                        "rzp145",
                        "rezaumbara@vale.com"});
#line 10
testRunner.And("Exist Employee AD user information From Common Service", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reason"});
            table14.AddRow(new string[] {
                        "Training"});
            table14.AddRow(new string[] {
                        "Emergency"});
            table14.AddRow(new string[] {
                        "Leave"});
#line 15
testRunner.And("Exist following overtime reasons", ((string)(null)), table14, "And ");
#line hidden
#line 21
testRunner.And("Todays date is \"19-FEB-2023\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1.Create Draft Claim by admin")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        [NUnit.Framework.CategoryAttribute("mockCommonService")]
        public virtual void _1_CreateDraftClaimByAdmin()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1",
                    "mockCommonService"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1.Create Draft Claim by admin", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "UserName",
                            "Password"});
                table15.AddRow(new string[] {
                            "admin@email.com",
                            "p@55wOrd"});
#line 25
 testRunner.Given("following user is logged in as admin", ((string)(null)), table15, "Given ");
#line hidden
#line 28
 testRunner.And("user able to select date from 30 days ago until today", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "EMPLOYEE_ID",
                            "NAME",
                            "POS_DEPT"});
                table16.AddRow(new string[] {
                            "0000007142",
                            "NASARUDDIN",
                            "SMELTER FURNACE"});
#line 29
 testRunner.And("user able to select these following employee data", ((string)(null)), table16, "And ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "EMPLOYEE_ID",
                            "NAME"});
                table17.AddRow(new string[] {
                            "0000007142",
                            "NASARUDDIN"});
#line 32
 testRunner.When("User Create new Claim with date \"19-FEB-2023\" and selected employees are", ((string)(null)), table17, "When ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "OT_NUMBER",
                            "OT_DATE",
                            "OT_HOUR",
                            "OT_REASON",
                            "EMPLOYEE_ID",
                            "NAME",
                            "POS_DEPT",
                            "POSITION_ID"});
                table18.AddRow(new string[] {
                            "OTS-0000-02-2023-7142",
                            "19-02-2023",
                            "<null>",
                            "<null>",
                            "0000007142",
                            "NASARUDDIN",
                            "SMELTER FURNACE",
                            "FPOCR4"});
#line 35
 testRunner.Then("Exist following overtime data with status \"DRAFT\"", ((string)(null)), table18, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Label",
                            "Input"});
                table19.AddRow(new string[] {
                            "OT_HOUR",
                            "4"});
                table19.AddRow(new string[] {
                            "OT_REASON",
                            "Training"});
#line 38
 testRunner.When("User submit an overtime with ot number \"OTS-0000-02-2023-7142\" with following ent" +
                        "ries", ((string)(null)), table19, "When ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "OT_NUMBER",
                            "OT_DATE",
                            "OT_HOUR",
                            "OT_REASON",
                            "EMPLOYEE_ID",
                            "NAME",
                            "POS_DEPT",
                            "POSITION_ID",
                            "FIRST_APPROVER_ID",
                            "FIRST_APPROVER_NAME",
                            "SECONDARY_APPROVER_ID",
                            "SECONDARY_APPROVER_NAME"});
                table20.AddRow(new string[] {
                            "OTS-0000-02-2023-7142",
                            "19-02-2023",
                            "4",
                            "Training",
                            "0000007142",
                            "NASARUDDIN",
                            "SMELTER FURNACE",
                            "FPOCR4",
                            "0000005664",
                            "MUJAHID LAOLA",
                            "0000008989",
                            "REZA PRIBADI UMBARA"});
#line 43
 testRunner.Then("Exist following overtime data with status \"WAITING FOR FIRST APPROVAL\"", ((string)(null)), table20, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
