// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowProjectGDIApps.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SimpleOvertimeApproval")]
    public partial class SimpleOvertimeApprovalFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "SimpleOvertimeApproval.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "SimpleOvertimeApproval", "A short summary of the feature", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "EMPLOYEE_ID",
                        "NAME",
                        "POSITION_ID",
                        "POS_DEPT",
                        "SUPERIOR_NAME",
                        "SUPERIOR_POS",
                        "MOR_NAME",
                        "MOR_POS"});
            table21.AddRow(new string[] {
                        "0000007142",
                        "NASARUDDIN",
                        "FPOCR4",
                        "SMELTER FURNACE",
                        "0000005664 - MUJAHID LAOLA",
                        "E00124 - SUPV, FURNACE SHIFT D",
                        "0000008989 - REZA PRIBADI UMBARA",
                        "DPPGM5 - MGR, SMELTER FURNAC"});
#line 5
testRunner.Given("Exist Following Employees Data From Common Service", ((string)(null)), table21, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "EMPLOYEE_ID",
                        "FULL_NAME",
                        "USERNAME",
                        "EMAIL"});
            table22.AddRow(new string[] {
                        "0000007142",
                        "NASARUDIN",
                        "nzr150",
                        "nasarudin@vale.com"});
            table22.AddRow(new string[] {
                        "0000005664",
                        "MUJAHID LAOLA",
                        "mu3210",
                        "mujahid.laola@vale.com"});
            table22.AddRow(new string[] {
                        "0000008989",
                        "REZA PRIBADI UMBARA",
                        "rzp145",
                        "rezaumbara@vale.com"});
#line 8
testRunner.And("Exist Employee AD user information From Common Service", ((string)(null)), table22, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2.Approval by First Approver")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public virtual void _2_ApprovalByFirstApprover()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2.Approval by First Approver", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 14
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "EMPLOYEE_ID",
                            "FULL_NAME",
                            "USERNAME",
                            "EMAIL"});
                table23.AddRow(new string[] {
                            "0000005664",
                            "MUJAHID LAOLA",
                            "mu3210",
                            "mujahid.laola@vale.com"});
#line 15
 testRunner.Given("Following user is logged in as \"TEAMLEADER\" at Screen Approval", ((string)(null)), table23, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "OT_NUMBER",
                            "OT_DATE",
                            "OT_HOUR",
                            "OT_REASON",
                            "EMPLOYEE_ID",
                            "NAME",
                            "POS_DEPT",
                            "POSITION_ID",
                            "FIRST_APPROVER_ID",
                            "FIRST_APPROVER_NAME",
                            "SECONDARY_APPROVER_ID",
                            "SECONDARY_APPROVER_NAME"});
                table24.AddRow(new string[] {
                            "OTS-0000-01-22-7142",
                            "19-01-2022",
                            "4",
                            "01",
                            "0000007142",
                            "NASARUDDIN",
                            "SMELTER FURNACE",
                            "FPOCR4",
                            "0000005664",
                            "MUJAHID LAOLA",
                            "0000008989",
                            "REZA PRIBADI UMBARA"});
#line 18
 testRunner.And("Exist following overtime data with status \"WAITING FOR FIRST APPROVAL\"", ((string)(null)), table24, "And ");
#line hidden
#line 21
 testRunner.When("User Approve overtime with OT Number \"OTS-0000-01-22-7142\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "OT_NUMBER",
                            "OT_DATE",
                            "OT_HOUR",
                            "OT_REASON",
                            "EMPLOYEE_ID",
                            "NAME",
                            "POS_DEPT",
                            "POSITION_ID",
                            "FIRST_APPROVER_ID",
                            "FIRST_APPROVER_NAME",
                            "SECONDARY_APPROVER_ID",
                            "SECONDARY_APPROVER_NAME"});
                table25.AddRow(new string[] {
                            "OTS-0000-01-22-7142",
                            "19-01-2022",
                            "4",
                            "01",
                            "0000007142",
                            "NASARUDDIN",
                            "SMELTER FURNACE",
                            "FPOCR4",
                            "0000005664",
                            "MUJAHID LAOLA",
                            "0000008989",
                            "REZA PRIBADI UMBARA"});
#line 22
 testRunner.Then("Exist following overtime data with status \"WAITING FOR SECOND APPROVAL\"", ((string)(null)), table25, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3.Approval by Second approver")]
        public virtual void _3_ApprovalBySecondApprover()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3.Approval by Second approver", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 26
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "EMPLOYEE_ID",
                            "FULL_NAME",
                            "USERNAME",
                            "EMAIL"});
                table26.AddRow(new string[] {
                            "0000008989",
                            "REZA PRIBADI UMBARA",
                            "rzp145",
                            "rezaumbara@vale.com"});
#line 27
 testRunner.Given("Following user is logged in as \"TEAMLEADER\" at Screen Approval", ((string)(null)), table26, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "OT_NUMBER",
                            "OT_DATE",
                            "OT_HOUR",
                            "OT_REASON",
                            "EMPLOYEE_ID",
                            "NAME",
                            "POS_DEPT",
                            "POSITION_ID",
                            "FIRST_APPROVER_ID",
                            "FIRST_APPROVER_NAME",
                            "SECONDARY_APPROVER_ID",
                            "SECONDARY_APPROVER_NAME"});
                table27.AddRow(new string[] {
                            "OTS-0000-01-22-7142",
                            "19-01-2022",
                            "4",
                            "01",
                            "0000007142",
                            "NASARUDDIN",
                            "SMELTER FURNACE",
                            "FPOCR4",
                            "0000005664",
                            "MUJAHID LAOLA",
                            "0000008989",
                            "REZA PRIBADI UMBARA"});
#line 30
 testRunner.And("Exist following overtime data with status \"WAITING FOR SECOND APPROVAL\"", ((string)(null)), table27, "And ");
#line hidden
#line 33
 testRunner.When("User Approve overtime with OT Number \"OTS-0000-01-22-7142\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "OT_NUMBER",
                            "OT_DATE",
                            "OT_HOUR",
                            "OT_REASON",
                            "EMPLOYEE_ID",
                            "NAME",
                            "POS_DEPT",
                            "POSITION_ID",
                            "FIRST_APPROVER_ID",
                            "FIRST_APPROVER_NAME",
                            "SECONDARY_APPROVER_ID",
                            "SECONDARY_APPROVER_NAME"});
                table28.AddRow(new string[] {
                            "OTS-0000-01-22-7142",
                            "19-01-2022",
                            "4",
                            "01",
                            "0000007142",
                            "NASARUDDIN",
                            "SMELTER FURNACE",
                            "FPOCR4",
                            "0000005664",
                            "MUJAHID LAOLA",
                            "0000008989",
                            "REZA PRIBADI UMBARA"});
#line 34
 testRunner.Then("Exist following overtime data with status \"APPROVED\"", ((string)(null)), table28, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
